BankingSite/Models/BankingSiteDb.cs
using System.Data.Entity;

namespace BankingSite.Models
{
    public class BankingSitedDb : DbContext
    {
        public BankingSitedDb()
            : base("name=DefaultConnection")
        {
        }        

        public DbSet<LoanApplication> LoanApplications { get; set; }        
    }
}

BankingSite/Models/BankingSiteDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BankingSite.Models
{
    public class BankingSiteDbInitializer : System.Data.Entity.DropCreateDatabaseAlways<BankingSitedDb>
    {

    }
}

BankingSite/Models/CreditHistoryChecker.cs
namespace BankingSite.Models
{
    public class CreditHistoryChecker : ICreditHistoryChecker
    {
        public bool CheckCreditHistory(string firstName, string lastName)
        {
            // Simulate actual credit check

            if (firstName.ToUpperInvariant() == "SARAH" 
                && lastName.ToUpperInvariant() == "SMITH")
            {
                return false;
            }

            return true;
        }
    }
}

BankingSite/Models/ICreditHistoryChecker.cs
namespace BankingSite.Models
{
    public interface ICreditHistoryChecker
    {
        bool CheckCreditHistory(string firstName, string lastName);
    }
}

BankingSite/Models/ILoanApplicationScorer.cs
namespace BankingSite.Models
{
    public interface ILoanApplicationScorer
    {
        void ScoreApplication(LoanApplication application);
    }
}

BankingSite/Models/IRepository.cs
namespace BankingSite.Models
{
    public interface IRepository
    {
        void Create(LoanApplication application);
        LoanApplication Find(int id);
    }
}

BankingSite/Models/InterestRates.cs
namespace BankingSite.Models
{
    public class InterestRates
    {
        public decimal LoanRate { get; set; }
        public decimal CreditCardRate { get; set; }
        public decimal TermDepositRate { get; set; }
    }
}

BankingSite/Models/LoanApplication.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BankingSite.Models
{    
    public class LoanApplication
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        [DisplayName("Current age in Years")]
        public int Age { get; set; }

        [Required]
        [DisplayName("Total Annual Pre-Tax Income")]
        
        public Decimal AnnualIncome { get; set; }

        public bool IsAccepted { get; set; }
    }  
}

BankingSite/Models/LoanApplicationScorer.cs
namespace BankingSite.Models
{
    public class LoanApplicationScorer : ILoanApplicationScorer
    {
        private readonly ICreditHistoryChecker _creditHistoryChecker;

        public LoanApplicationScorer(ICreditHistoryChecker creditHistoryChecker)
        {
            _creditHistoryChecker = creditHistoryChecker;
        }

        public void ScoreApplication(LoanApplication application)
        {
            var isBasicCriteriaMet = ValidateBasicCriteria(application);

            if (isBasicCriteriaMet)
            {
                var isCreditHistoryGood = 
                    _creditHistoryChecker.CheckCreditHistory(
                                            application.FirstName,
                                            application.LastName);

                application.IsAccepted = isCreditHistoryGood;
            }
            else
            {
                application.IsAccepted = false;
            }
        }

        private bool ValidateBasicCriteria(LoanApplication application)
        {
            // Basic simulated business rules

            // If applicant earns over a million dollars then 
            // other criteria don't matter
            if (application.AnnualIncome > 1000000)
            {
                return true;
            }

            // Don't lend to younger applicants
            if (application.Age <= 21)
            {
                return false;
            }

            return true;
        }
    }
}

BankingSite/Models/Repository.cs
namespace BankingSite.Models
{
    public class Repository : IRepository
    {      
        public void Create(LoanApplication application)
        {
            using (var db = new BankingSitedDb())
            {
                db.LoanApplications.Add(application);
                db.SaveChanges();
            }            
        }

        public LoanApplication Find(int id)
        {
            using (var db = new BankingSitedDb())
            {
                return db.LoanApplications.Find(id);
            }              
        }
    }
}

BankingSite/Controllers/HomeController.cs
using System.Web.Mvc;
using BankingSite.Models;

namespace BankingSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Apply today for our award winning personal loans.";

            // Hard-coded rates for demo purposes
            var rates = new InterestRates
                        {
                            CreditCardRate = 22.33m,
                            LoanRate = 9.24m,
                            TermDepositRate = 5.2m
                        };

            return View(rates);
        }   

        public ActionResult Contact()
        {
            return Redirect("http://pluralsight.com");
        }
    }
}

BankingSite/Controllers/LoanApplicationController.cs
using System.Web.Mvc;
using BankingSite.Models;

namespace BankingSite.Controllers
{
    public class LoanApplicationController : Controller
    {
        private readonly IRepository _repository;
        private readonly ILoanApplicationScorer _scorer;

        public LoanApplicationController(IRepository repository, ILoanApplicationScorer scorer)
        {
            _repository = repository;
            _scorer = scorer;
        }


        public ActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Apply(LoanApplication application)
        {
            if (!ModelState.IsValid)
            {
                return View(application);
            }

            _scorer.ScoreApplication(application);

            _repository.Create(application);

            if (application.IsAccepted)
            {
                return RedirectToAction("Accepted", new { id = application.ID });
            }
            else
            {
                return RedirectToAction("Declined", new { id = application.ID });
            }
        }


        public ActionResult Accepted(int id)
        {
            var application = _repository.Find(id);

            return View(application);
        }

        public ActionResult Declined(int id)
        {
            var application = _repository.Find(id);

            return View(application);            
        }
    }
}

BankingSite/Controllers/LoanApplicationSearchController.cs
using System.Web.Mvc;
using BankingSite.Models;

namespace BankingSite.Controllers
{
    public class LoanApplicationSearchController : Controller
    {
        private readonly IRepository _repository;

        public LoanApplicationSearchController(IRepository repository)
        {
            _repository = repository;
        }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ApplicationStatus(int applicationId)
        {
            var application = _repository.Find(applicationId);

            if (application == null)
            {
                return HttpNotFound();
            }

            return View(application);
        }
    }
}

BankingSite/Views/Home/Index.cshtml
@model BankingSite.Models.InterestRates

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Low rate loan!</h1>
    <p class="lead" id="mainMessage">@ViewBag.Message</p>
    <p>Current loan rate: <span id="loanRate">@Model.LoanRate</span> %</p>
    <p><a href="@Url.Action("Apply", "LoanApplication")" class="btn btn-primary btn-lg">Apply Now ! &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Tempor illum</h2>
        <p>Illum amet dolore sadipscing amet magna consectetuer diam nisl. Adipiscing diam aliquyam ad est ut eleifend eu dolores commodo diam clita est accusam id. </p>
        <p><a class="btn btn-default" href="">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Eirmod stet dignissim</h2>
        <p>Dolore stet stet duis lorem accumsan invidunt assum ut in duo wisi diam. Et vulputate invidunt dolore facilisis accusam in dolore clita dolore at in clita consectetuer.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Et facilisis</h2>
        <p>Et volutpat aliquip consetetur magna ut consectetuer accusam aliquip ipsum. In consetetur justo diam at aliquyam duis erat dolor praesent.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BankingSite/Views/LoanApplication/Accepted.cshtml
@model BankingSite.Models.LoanApplication

@{
    ViewBag.Title = "Loan Application";
}

<h2 id="acceptMessage">Congratulations @Model.FirstName - Your application was accepted!</h2>

<h3>Your reference number is: @Model.ID</h3>
<div>
    <h4>Loan Application Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.AnnualIncome)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.AnnualIncome)
        </dd>
    </dl>
</div>

BankingSite/Views/LoanApplication/Apply.cshtml
@model BankingSite.Models.LoanApplication

@{
    ViewBag.Title = "Loan Application";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Application Details</legend>

        <div>
            @Html.LabelFor(model => model.FirstName)
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div>
            @Html.LabelFor(model => model.LastName)
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>        
        
        <div>
            @Html.LabelFor(model => model.Age)
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)
        </div>
        
        <div>
            @Html.LabelFor(model => model.AnnualIncome)
            @Html.EditorFor(model => model.AnnualIncome)
            @Html.ValidationMessageFor(model => model.AnnualIncome)
        </div>        

        <p>
            <input type="submit" value="Apply" id="Apply" class="btn btn-primary" />
        </p>
    </fieldset>
}

BankingSite/Views/LoanApplication/Declined.cshtml
@model BankingSite.Models.LoanApplication

@{
    ViewBag.Title = "Loan Application";
}

<h2 id="declineMessage">Sorry @Model.FirstName - We are unable to offer you a loan at this time.</h2>

<p>If you feel you may be able to provide further details to support your application, please ring us quoting reference number: @Model.ID</p>

BankingSite/Views/LoanApplicationSearch/ApplicationStatus.cshtml
@model BankingSite.Models.LoanApplication

@{
    ViewBag.Title = "Loan Application Status";    
}

<h2>@ViewBag.Title</h2>

<h3 id="firstName">@Model.FirstName</h3>

<h3 id="status">
    @if (Model.IsAccepted){
        <span id="acceptedMessage">Yay! Accepted!</span>
    }
    else
    {
        <span id="declinedMessage">Sorry. Declined.</span>
    }
</h3>

BankingSite/Views/LoanApplicationSearch/Index.cshtml
@{
    ViewBag.Title = "Loan Application Status Search";
}

<h2>@ViewBag.Title</h2>

@using (@Html.BeginForm("ApplicationStatus", "LoanApplicationSearch", FormMethod.Get))
{
    <div class="input-group">
        <input type="search" name="applicationId" class="form-control" placeholder="reference number" />
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
}

BankingSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Banking Site</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Banking Site", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Application Status", "Index", "LoanApplicationSearch")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Banking Site</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>